### ISSUE TITLE
Start a category for pt_BR links

### ISSUE THREAD

**Issue by andy5995** [mhwkb/mhwkb.github.io#113]
To create a new category, add pt_BR.html to the jekyll/category/ directory [jekyll/category/](https://github.com/mhwkb/mhwkb.github.io/tree/master/jekyll/category)

The contents of that file should be

```
---
layout: category_index
title: Brasilian Portuguese
permalink: /category/pt_BR/
category: pt_BR
pagination:
    enabled: true
    category: pt_BR
    permalink: /:num/
---
```

The actual link go into [jekyll/_posts](https://github.com/mhwkb/mhwkb.github.io/tree/master/jekyll/_posts) and detailed instructions are at https://github.com/mhwkb/mhwkb.github.io/issues/11

Thanks, @localhostpedro :)
